### ISSUE TITLE
Can't access package private game class despite same namespace

### ISSUE THREAD

**Issue by 4rg0n** [4rg0n/songs-of-syx-mod-plant-trees#1]
It seems that when running the game via the `.exe` the `settlement.job.PlantTreeJob` class is unable to access the games `settlement.job.JobBuild`. That **could be** because `script.SCRIPT` classes are initialized with their own ClassLoader.

When starting the game via the `SongsOfSyx.jar` from an IDE, `settlement.job.JobBuild` can be accessed.

```
java.lang.IllegalAccessError: class settlement.job.PlantTreeJob cannot access its superclass settlement.job.JobBuild
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Unknown Source)
	at java.lang.Class.getConstructor0(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at script.ScriptLoad$Init.loadScripts(ScriptLoad.java:192)
	at script.ScriptLoad$Init.compileScripts(ScriptLoad.java:137)
	at script.ScriptLoad$Init.access$0(ScriptLoad.java:103)
	at script.ScriptLoad.getAll(ScriptLoad.java:41)
	at menu.ScRandom$ScripSelector.<init>(ScRandom.java:354)
	at menu.ScRandom$ScripSelector.<init>(ScRandom.java:352)
	at menu.ScRandom.<init>(ScRandom.java:46)
	at menu.Menu.<init>(Menu.java:94)
	at menu.Menu.make(Menu.java:75)
	at menu.Menu$2.getState(Menu.java:59)
	at snake2d.Updater.run(Updater.java:39)
```

Currently I don't know how to work around that.

**Comment by 4rg0n** [comment]
Aaand he's done it =D
